In [31]:
!pip install ultralytics deep_sort_realtime opencv-python-headless


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 796.9/796.9 kB 13.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 72.3 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylin

In [32]:
!pip install wget

  Preparing metadata (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9656 sha256=a79aabc7e01de076b4dc5d901c875d2ed4c9aa565ac7c987d72b6e5bc0cef531
  Stored in directory: /root/.cache/pip/wheels/8b/f1/7f/5c94f0a7a505ca1c81cd1d9208ae2064675d97582078e6c769
Successfully built wget


In [37]:
from google.colab import files
uploaded = files.upload()


Saving yt1s.com - Man walk cycle happy walking side view reference Animation Reference Videos_1080p.mp4 to yt1s.com - Man walk cycle happy walking side view reference Animation Reference Videos_1080p.mp4


In [43]:
!git clone https://github.com/abewley/sort.git
%cd sort
!pip install -r requirements.txt


Cloning into 'sort'...
remote: Enumerating objects: 208, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 208 (delta 2), reused 2 (delta 1), pack-reused 202
Receiving objects: 100% (208/208), 1.21 MiB | 3.13 MiB/s, done.
Resolving deltas: 100% (74/74), done.
/content/sort
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.0/178.0 kB 4.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.8/29.8 MB 17.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 19.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for filterpy: filename=filterpy-1.4.5-py3-none-any.whl size=110458 sha256=b21083b9a34dbc847b6f89ffb2ef0b0ed1df51652dedde4547977aeafcb7e203
  Stored in directory: /root/.cache/pip/wheels/0f/0c/ea/218f266af4ad626897562199fbbcba521b8497303200186102
  Created wheel for scikit-image: file

In [44]:
import cv2
import numpy as np
import random
from ultralytics import YOLO

# Initialize YOLOv8 segmentation model
model = YOLO("yolov8m-seg.pt")

# Load video file
video_path = "/content/yt1s.com - Man walk cycle happy walking side view reference Animation Reference Videos_1080p.mp4"  # Replace with the path to your uploaded video
video_capture = cv2.VideoCapture(video_path)

# Define a codec and create VideoWriter object to save the output
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter('output.mp4', fourcc, 20.0, (int(video_capture.get(3)), int(video_capture.get(4))))

# Get class names and colors
yolo_classes = list(model.names.values())
classes_ids = [yolo_classes.index(clas) for clas in yolo_classes]
colors = [random.choices(range(256), k=3) for _ in classes_ids]

# Processing video frames
while video_capture.isOpened():
    ret, frame = video_capture.read()
    if not ret:
        break

    # Predict with YOLO model
    conf = 0.5
    results = model.predict(frame, conf=conf)

    # Overlay segmentation masks on the frame
    for result in results:
        for mask, box in zip(result.masks.xy, result.boxes):
            points = np.int32([mask])
            color_number = classes_ids.index(int(box.cls[0]))
            cv2.fillPoly(frame, points, colors[color_number])

    # Write the frame with the segmentation masks
    out.write(frame)

# Release video objects
video_capture.release()
out.release()

print("Processing complete. Output saved as 'output.mp4'.")


100%|██████████| 52.4M/52.4M [00:00<00:00, 256MB/s]



0: 384x640 4 persons, 1 car, 1938.2ms
Speed: 12.9ms preprocess, 1938.2ms inference, 23.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 persons, 1 car, 2006.4ms
Speed: 4.1ms preprocess, 2006.4ms inference, 18.6ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 persons, 1 car, 1109.7ms
Speed: 3.6ms preprocess, 1109.7ms inference, 11.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 persons, 1 car, 1185.2ms
Speed: 4.1ms preprocess, 1185.2ms inference, 40.4ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 persons, 1 car, 2046.9ms
Speed: 3.9ms preprocess, 2046.9ms inference, 19.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 persons, 1 car, 2128.3ms
Speed: 6.5ms preprocess, 2128.3ms inference, 19.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 persons, 1 car, 2407.5ms
Speed: 4.5ms preprocess, 2407.5ms inference, 41.5ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 4 persons, 1 c

In [45]:
from google.colab import files
files.download('output.mp4')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
# tensors common functions refresher


In [1]:
import tensorflow as tf

In [26]:
zero_dimension_tensor = tf.constant(12)

print(zero_dimension_tensor)

tf.Tensor(12, shape=(), dtype=int32)


In [24]:
one_dimension_tensor = tf.constant([1,0,4,5], dtype=tf.float32)

#casting to int
casted_dimension_tensor = tf.cast(one_dimension_tensor, dtype=tf.bool)

print(one_dimension_tensor)
print(casted_dimension_tensor)

tf.Tensor([1. 0. 4. 5.], shape=(4,), dtype=float32)
tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


In [10]:
two_dimension_tensor = tf.constant([
    [1,2,3.],
    [4,5,6]
])

print(two_dimension_tensor)


tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [13]:
three_dimension_tensor = tf.constant(
    [
        [
            [1,2,3],
            [4,5,6]
        ],
        [
            [7,8,9],
            [10,11,12]
        ]
    ]



)

print (three_dimension_tensor.shape)

(2, 2, 3)


In [14]:
# prompt: 4 d tensor

import tensorflow as tf

four_dimension_tensor = tf.constant(
    [
        [
            [
                [1,2,3],
                [4,5,6]
            ],
            [
                [7,8,9],
                [10,11,12]
            ]
        ],
        [
            [
                [13,14,15],
                [16,17,18]
            ],
            [
                [19,20,21],
                [22,23,24]
            ]
        ]
    ]
)

print(four_dimension_tensor.shape)


(2, 2, 2, 3)


In [27]:
#numpy array
import numpy as np

numpy_array = np.array([1,2,3])

print(numpy_array)

[1 2 3]


In [28]:
converted_tensor = tf.convert_to_tensor(numpy_array)

print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [47]:
# prompt: eye tf with 3 rows two columns

identity_matrix = tf.eye(
    num_rows=3,
    num_columns=2,
    batch_shape=None,
    dtype=tf.int32

    )
print(identity_matrix)


tf.Tensor(
[[1 0]
 [0 1]
 [0 0]], shape=(3, 2), dtype=int32)
